import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// Integrated Gemini REST Proxy (Resilient & Robust)
const geminiProxy = () => ({
  name: 'gemini-proxy',
  configureServer(server: any) {
    server.middlewares.use(async (req: any, res: any, next: any) => {
      if (req.url === '/api/analyze' && req.method === 'POST') {
        let body = '';
        req.on('data', (chunk: any) => { body += chunk; });
        req.on('end', async () => {
          try {
            if (!body) {
              res.statusCode = 400;
              return res.end(JSON.stringify({ error: "Empty request body" }));
            }

            const { prompt, modelName, apiKey } = JSON.parse(body);
            
            if (!apiKey || !apiKey.trim()) {
              res.statusCode = 400;
              return res.end(JSON.stringify({ error: "API Key missing" }));
            }

            const model = modelName || 'gemini-2.0-flash';
            const trimmedKey = apiKey.trim();
            
            console.log(`[Vite Proxy] 🚀 Processing request for ${model}...`);

            const response = await fetch(
              `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${trimmedKey}`,
              {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  contents: [{ parts: [{ text: prompt }] }],
                  generationConfig: {
                    responseMimeType: "application/json"
                  }
                })
              }
            );

            const responseText = await response.text();
            let data;
            try {
              data = JSON.parse(responseText);
            } catch (e) {
              console.error("[Vite Proxy] ❌ Failed to parse Gemini response:", responseText);
              res.statusCode = 500;
              return res.end(JSON.stringify({ error: "Invalid response from Gemini API" }));
            }

            if (!response.ok) {
              console.error("[Vite Proxy] ❌ Gemini API Error:", data);
              res.statusCode = response.status;
              return res.end(JSON.stringify({ 
                error: data.error?.message || "Gemini API Error",
                details: data.error 
              }));
            }

            const aiText = data.candidates?.[0]?.content?.parts?.[0]?.text;
            
            if (!aiText) {
              console.error("[Vite Proxy] ❌ No text in candidates:", data);
              res.statusCode = 500;
              return res.end(JSON.stringify({ error: "Empty narrative generated by AI" }));
            }

            res.setHeader('Content-Type', 'application/json');
            res.end(aiText);
            console.log(`[Vite Proxy] ✅ Success.`);
          } catch (error: any) {
            console.error(`[Vite Proxy] ❌ Internal Proxy Error:`, error);
            res.statusCode = 500;
            res.end(JSON.stringify({ error: error.message || "Internal Server Error" }));
          }
        });
      } else {
        next();
      }
    });
  }
});

export default defineConfig({
  plugins: [react(), tailwindcss(), geminiProxy()],
  server: {
    port: 3000,
    host: '0.0.0.0'
  }
});
