import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

// Integrated Gemini & Ollama Proxy
const aiProxy = () => ({
  name: 'ai-proxy',
  configureServer(server: any) {
    server.middlewares.use(async (req: any, res: any, next: any) => {
      if (req.url === '/api/analyze' && req.method === 'POST') {
        let body = '';
        req.on('data', (chunk: any) => { body += chunk; });
        req.on('end', async () => {
          try {
            if (!body) {
              res.statusCode = 400;
              return res.end(JSON.stringify({ error: "Empty request body" }));
            }

            const { prompt, modelName, apiKey } = JSON.parse(body);
            
            if (!apiKey || !apiKey.trim()) {
              res.statusCode = 400;
              return res.end(JSON.stringify({ error: "API Key missing" }));
            }

            const model = modelName || 'gemini-2.0-flash';
            const trimmedKey = apiKey.trim();
            
            console.log(`[AI Proxy] 🚀 Calling Gemini API (${model})...`);

            const response = await fetch(
              `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${trimmedKey}`,
              {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  contents: [{ parts: [{ text: prompt }] }],
                  generationConfig: {
                    responseMimeType: "application/json"
                  },
                  // Lower safety thresholds to prevent "PROHIBITED_CONTENT" blocks for romantic chat data
                  safetySettings: [
                    { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_ONLY_HIGH" },
                    { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_ONLY_HIGH" },
                    { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_ONLY_HIGH" },
                    { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_ONLY_HIGH" }
                  ]
                })
              }
            );

            const responseText = await response.text();
            let data;
            try {
              data = JSON.parse(responseText);
            } catch (e) {
              console.error("[AI Proxy] ❌ Failed to parse Gemini response:", responseText);
              res.statusCode = 500;
              return res.end(JSON.stringify({ error: "Invalid response from Gemini API" }));
            }

            if (!response.ok) {
              console.error("[AI Proxy] ❌ Gemini API Error:", data);
              res.statusCode = response.status;
              return res.end(JSON.stringify({ 
                error: data.error?.message || "Gemini API Error",
                details: data.error 
              }));
            }

            // Check if the content was blocked by safety filters
            if (data.promptFeedback?.blockReason === 'PROHIBITED_CONTENT') {
              console.error("[AI Proxy] ⚠️ Content blocked by Gemini safety filters.");
              res.statusCode = 422; // Unprocessable Entity
              return res.end(JSON.stringify({ 
                error: "The AI safety filters blocked this specific chapter of your story. Try a different model or re-run the analysis.",
                details: data.promptFeedback
              }));
            }

            const aiText = data.candidates?.[0]?.content?.parts?.[0]?.text;
            
            if (!aiText) {
              // Check if the candidate was blocked even if the prompt wasn't
              const finishReason = data.candidates?.[0]?.finishReason;
              if (finishReason === 'SAFETY') {
                res.statusCode = 422;
                return res.end(JSON.stringify({ error: "This response was filtered for safety. It's too soulful for the AI's current settings!" }));
              }

              console.error("[AI Proxy] ❌ No text in candidates:", data);
              res.statusCode = 500;
              return res.end(JSON.stringify({ error: "Empty narrative generated by AI" }));
            }

            res.setHeader('Content-Type', 'application/json');
            res.end(aiText);
            console.log(`[AI Proxy] ✅ Gemini Success.`);
          } catch (error: any) {
            console.error(`[AI Proxy] ❌ Internal Proxy Error:`, error);
            res.statusCode = 500;
            res.end(JSON.stringify({ error: error.message || "Internal Server Error" }));
          }
        });
      } else {
        next();
      }
    });
  }
});

export default defineConfig({
  plugins: [react(), tailwindcss(), aiProxy()],
  server: {
    port: 3000,
    host: '0.0.0.0'
  }
});
