export const COIN_MAP = {
  BTC: { id: 'bitcoin', name: 'Bitcoin', symbol: 'BTC' },
  ETH: { id: 'ethereum', name: 'Ethereum', symbol: 'ETH' },
  BNB: { id: 'binancecoin', name: 'BNB', symbol: 'BNB' },
  XRP: { id: 'ripple', name: 'XRP', symbol: 'XRP' },
  SOL: { id: 'solana', name: 'Solana', symbol: 'SOL' },
  ADA: { id: 'cardano', name: 'Cardano', symbol: 'ADA' },
  DOGE: { id: 'dogecoin', name: 'Dogecoin', symbol: 'DOGE' },
  TRX: { id: 'tron', name: 'TRON', symbol: 'TRX' },
  TON: { id: 'the-open-network', name: 'Toncoin', symbol: 'TON' },
  AVAX: { id: 'avalanche-2', name: 'Avalanche', symbol: 'AVAX' },
  SHIB: { id: 'shiba-inu', name: 'Shiba Inu', symbol: 'SHIB' },
  LINK: { id: 'chainlink', name: 'Chainlink', symbol: 'LINK' },
  DOT: { id: 'polkadot', name: 'Polkadot', symbol: 'DOT' },
  BCH: { id: 'bitcoin-cash', name: 'Bitcoin Cash', symbol: 'BCH' },
  NEAR: { id: 'near', name: 'NEAR Protocol', symbol: 'NEAR' },
  MATIC: { id: 'matic-network', name: 'Polygon', symbol: 'MATIC' },
  POL: { id: 'matic-network', name: 'Polygon', symbol: 'POL' },
  LTC: { id: 'litecoin', name: 'Litecoin', symbol: 'LTC' },
  ICP: { id: 'internet-computer', name: 'Internet Computer', symbol: 'ICP' },
  UNI: { id: 'uniswap', name: 'Uniswap', symbol: 'UNI' },
  APT: { id: 'aptos', name: 'Aptos', symbol: 'APT' },
  PEPE: { id: 'pepe', name: 'Pepe', symbol: 'PEPE' },
  XLM: { id: 'stellar', name: 'Stellar', symbol: 'XLM' },
  ATOM: { id: 'cosmos', name: 'Cosmos', symbol: 'ATOM' },
  OP: { id: 'optimism', name: 'Optimism', symbol: 'OP' },
  ARB: { id: 'arbitrum', name: 'Arbitrum', symbol: 'ARB' },
  FIL: { id: 'filecoin', name: 'Filecoin', symbol: 'FIL' },
  HBAR: { id: 'hedera-hashgraph', name: 'Hedera', symbol: 'HBAR' },
  VET: { id: 'vechain', name: 'VeChain', symbol: 'VET' },
  MKR: { id: 'maker', name: 'Maker', symbol: 'MKR' },
  AAVE: { id: 'aave', name: 'Aave', symbol: 'AAVE' },
  INJ: { id: 'injective-protocol', name: 'Injective', symbol: 'INJ' },
  SUI: { id: 'sui', name: 'Sui', symbol: 'SUI' },
  GRT: { id: 'the-graph', name: 'The Graph', symbol: 'GRT' },
  ALGO: { id: 'algorand', name: 'Algorand', symbol: 'ALGO' },
  SAND: { id: 'the-sandbox', name: 'The Sandbox', symbol: 'SAND' },
  MANA: { id: 'decentraland', name: 'Decentraland', symbol: 'MANA' },
  AXS: { id: 'axie-infinity', name: 'Axie Infinity', symbol: 'AXS' },
  XMR: { id: 'monero', name: 'Monero', symbol: 'XMR' },
  EOS: { id: 'eos', name: 'EOS', symbol: 'EOS' },
  ZEC: { id: 'zcash', name: 'Zcash', symbol: 'ZEC' },
  FLOW: { id: 'flow', name: 'Flow', symbol: 'FLOW' },
  USDT: { id: 'tether', name: 'Tether', symbol: 'USDT' },
  USDC: { id: 'usd-coin', name: 'USD Coin', symbol: 'USDC' },
  DAI: { id: 'dai', name: 'Dai', symbol: 'DAI' },
  BITCOIN: { id: 'bitcoin', name: 'Bitcoin', symbol: 'BTC' },
  ETHEREUM: { id: 'ethereum', name: 'Ethereum', symbol: 'ETH' },
  SOLANA: { id: 'solana', name: 'Solana', symbol: 'SOL' },
  DOGECOIN: { id: 'dogecoin', name: 'Dogecoin', symbol: 'DOGE' },
  CARDANO: { id: 'cardano', name: 'Cardano', symbol: 'ADA' },
  RIPPLE: { id: 'ripple', name: 'XRP', symbol: 'XRP' },
  POLKADOT: { id: 'polkadot', name: 'Polkadot', symbol: 'DOT' },
  POLYGON: { id: 'matic-network', name: 'Polygon', symbol: 'MATIC' },
  AVALANCHE: { id: 'avalanche-2', name: 'Avalanche', symbol: 'AVAX' },
  CHAINLINK: { id: 'chainlink', name: 'Chainlink', symbol: 'LINK' },
  UNISWAP: { id: 'uniswap', name: 'Uniswap', symbol: 'UNI' },
  LITECOIN: { id: 'litecoin', name: 'Litecoin', symbol: 'LTC' },
  COSMOS: { id: 'cosmos', name: 'Cosmos', symbol: 'ATOM' },
  STELLAR: { id: 'stellar', name: 'Stellar', symbol: 'XLM' },
  MONERO: { id: 'monero', name: 'Monero', symbol: 'XMR' },
  OPTIMISM: { id: 'optimism', name: 'Optimism', symbol: 'OP' },
  ARBITRUM: { id: 'arbitrum', name: 'Arbitrum', symbol: 'ARB' },
};

export const CACHE_TTL_MS = 45_000;

export const ALERT_REPEAT_INTERVALS = {
  once: 0,
  '5m': 300_000,
  '15m': 900_000,
  '30m': 1_800_000,
  '60m': 3_600_000,
};

export const DEFAULT_SETTINGS = {
  currency: 'usd',
  currencySymbol: '$',
  watchlist: ['bitcoin', 'ethereum', 'solana', 'binancecoin', 'ripple'],
  tooltipEnabled: true,
  tooltipDelay: 400,
  refreshInterval: 60,
  theme: 'dark',
  alertsEnabled: true,
  alerts: [],
  portfolio: [],
  gasTrackerEnabled: true,
  compactMode: false,
};

export const CURRENCIES = [
  { code: 'usd', symbol: '$', name: 'US Dollar' },
  { code: 'eur', symbol: '€', name: 'Euro' },
  { code: 'gbp', symbol: '£', name: 'British Pound' },
  { code: 'jpy', symbol: '¥', name: 'Japanese Yen' },
  { code: 'aud', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'cad', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'chf', symbol: 'Fr', name: 'Swiss Franc' },
  { code: 'cny', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'btc', symbol: '₿', name: 'Bitcoin' },
  { code: 'eth', symbol: 'Ξ', name: 'Ethereum' },
];

export const COIN_COLORS = {
  bitcoin: '#f7931a',
  ethereum: '#627eea',
  solana: '#9945ff',
  binancecoin: '#f3ba2f',
  ripple: '#346aa9',
  cardano: '#0033ad',
  dogecoin: '#c2a633',
  'the-open-network': '#0088cc',
  'avalanche-2': '#e84142',
  'shiba-inu': '#ffa409',
  chainlink: '#2a5ada',
  polkadot: '#e6007a',
  'bitcoin-cash': '#8dc351',
  near: '#00c1de',
  'matic-network': '#8247e5',
  litecoin: '#bfbbbb',
  uniswap: '#ff007a',
  aptos: '#2de4c0',
  stellar: '#7d00ff',
  cosmos: '#6f7390',
  optimism: '#ff0420',
  arbitrum: '#12aaff',
  monero: '#ff6600',
  maker: '#1aab9b',
  aave: '#b6509e',
  'injective-protocol': '#00b2ff',
  sui: '#4da2ff',
  tron: '#ff0013',
  algorand: '#ffffff',
  filecoin: '#0090ff',
  'hedera-hashgraph': '#8259ef',
  vechain: '#15bdff',
  pepe: '#00c814',
  'internet-computer': '#f15a24',
  'the-graph': '#6f41d8',
  'the-sandbox': '#00adef',
  decentraland: '#ff2d55',
  'axie-infinity': '#0055d5',
  eos: '#443f54',
  zcash: '#f4b728',
  flow: '#00ef8b',
  tether: '#26a17b',
  'usd-coin': '#2775ca',
  dai: '#f5ac37',
};
